### ISSUE TITLE
[M0 - Dev] Relación entre usuarios, gastos comunes y deudas

### ISSUE THREAD

**Issue by danielsp13** [jesusjmma/Proyecto-Infraestructura-Virtual#10]
En este issue se plantea uno de los problemas más importantes que he observado tras el análisis del dominio de este proyecto. En particular, me baso en las historias de usuario [HU2](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/3) y [HU3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/4). 

De ambas historias, y también apoyado en los user-journeys, uno de los diferentes problemas es cómo se trata la relación que mantiene un usuario, con sus respectivas deudas, y el papel que desempeñan los gastos comunes en los que participan un conjunto de usuarios:

* Por una parte, en [HU3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/4), Jose Antonio necesita poder tener un control personal de lo que debe. Por tanto, esto indica que desde el punto de vista de un usuario, se debe poder recuperar todas las deudas que tiene con respecto a otros usuarios, con la información tal y como se indica aquí.

* Por otra parte, en [HU2](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/3), María Teresa necesita tener un control de las personas con las que comparte un determinado gasto (por ejemplo, se puede acudir al user-journey correspondiente a esta HU), además de verificar, una vez se haya decidido quién debe a quién y qué cantidad, las personas que han resuelto su deuda.

**Comment by danielsp13** [comment]
Tras el análisis de lo anterior, aquí planteo mi solución. Está claro que se necesita una entidad que permita modelar un contexto que involucre a una serie de personas y a una serie de gastos, con el objetivo de generar unas deudas que asocian únicamente a pares de usuarios. 

A eso es a lo que he llamado *gastoCompartido*, una entidad que sitúa a un conjunto de usuarios y a un conjunto de gastos producidos por un subconjunto de personas participantes, bajo un mismo contexto, para acto seguido poder identificar todo lo mencionado en las historias de usuario. 

No obstante, también se necesita que en la entidad referente al *usuario*, se pueda acceder directamente a las deudas que tiene esa persona en los diferentes contextos que se han producido, por lo que en dicha clase (se abordará en otro issue) se mantendrá un listado con dicha información.

Lo que se consigue con esto:
1. Desde un punto de vista como el de María Teresa, el poder recuperar fácilmente la información de lo que ha pagado cada uno, de lo que debe cada uno y quién ha pagado ya su respectiva deuda. 
2. Desde un punto de vista como el de José Antonio, el poder recuperar a través de su usuario todas las deudas que mantiene en las diferentes situaciones en las que se ha producido.

Por último, hay que tener en cuenta que la producción de un gasto no tiene sentido fuera de una situación en la que no intervengan un mínimo de dos usuarios, puesto que si no, la lógica de negocio no tendría nada de particular, ya que la idea es que se describa una situación con varios participantes y se generen y *determine*, las deudas más eficientes, tal y como se especifica en la documentación de este proyecto

**Comment by danielsp13** [comment]
@jesusjmma , por favor, asigna este issue a tu milestone M0.

**Comment by danielsp13** [comment]
Además, coméntame qué te parece la solución que planteo para el caso de estudio que te he puesto de ejemplo.

**Comment by danielsp13** [comment]
Renombro de esta forma el issue debido a la consecución lógica que deberían tener los acontecimientos tal y como se especifican en las historias de usuario correspondientes:

1. Identificar el gasto compartido.
2. Identificar los participantes.
3. Identificar los gastos que se han producido bajo el marco del gasto compartido, quién lo realizó y  quiénes participan.
4. Generar las deudas oportunas.

**Comment by JJ** [comment]
Sería bastante conveniente que trabajaras sólo con una historia de usuario, y priorizaras lo necesario de una con respecto a otra (para ello, @jesusjmma debería haber escogido una sola para este milestone, pero da igual).
En lo que consiste el diseño dirigido por dominio es identificar los átomos fundamentales de este problema, "tirando del hilo" desde el nivel más alto hasta llegar a lo más simple.
En ese sentido, la identificación usuario-problema-voy a ponerme a trabajar en esto generalmente lleva a una mala modelización. El camino correcto es
1. Crear diferentes issues, relacionados entre sí, que vayan identificando las diferentes partes del problema.
2. Llegar a lo más simple.
3. Programar eso tan simple, que será un objeto valor.

Lo que has hecho aquí en comentarios no clarifica nada el problema, y menos para la persona que revisa, que básicamente tienen que mirar al código y decir "ha hecho esto porque..." Pero el problema fundamental no es ese. El problema es que no has llegado a lo más simple, y te has puesto a programar antes. ¿Qué es lo más simple?

**Comment by danielsp13** [comment]
> Sería bastante conveniente que trabajaras sólo con una historia de usuario, y priorizaras lo necesario de una con respecto a otra (para ello, @jesusjmma debería haber escogido una sola para este milestone, pero da igual). En lo que consiste el diseño dirigido por dominio es identificar los átomos fundamentales de este problema, "tirando del hilo" desde el nivel más alto hasta llegar a lo más simple. En ese sentido, la identificación usuario-problema-voy a ponerme a trabajar en esto generalmente lleva a una mala modelización. El camino correcto es
> 
> 1. Crear diferentes issues, relacionados entre sí, que vayan identificando las diferentes partes del problema.
> 2. Llegar a lo más simple.
> 3. Programar eso tan simple, que será un objeto valor.
> 
> Lo que has hecho aquí en comentarios no clarifica nada el problema, y menos para la persona que revisa, que básicamente tienen que mirar al código y decir "ha hecho esto porque..." Pero el problema fundamental no es ese. El problema es que no has llegado a lo más simple, y te has puesto a programar antes. ¿Qué es lo más simple?

Comprendo que la solución debe explicarse claramente en código, en su respectivo commit, en la documentación oportuna, y no aquí en un comentario.
Mi problema entiendo que ha estado en considerar las dos historias de usuario a la vez. Ya que lo más simple que he considerado es la historia de usuario número 3, en la que las únicas diferentes partes del problema son, las deudas y su relación con los usuarios de manera individual.

Yo creo que nada más simple puede haber ya...

**Comment by JJ** [comment]
¿Seguro que lo más simple son las deudas? ¿Has leído bien las historias de usuario?
