### ISSUE TITLE
[M0 - Dev] Definición de deuda

### ISSUE THREAD

**Issue by danielsp13** [jesusjmma/Proyecto-Infraestructura-Virtual#12]
En este issue planteo el problema de la definición correcta de lo que supone una deuda en el contexto en que se ha mencionado en #10 , concepto surgido tras abordar la relación entre un usuario, las *deudas*, y gastos.

Para este problema, vuelvo a acudir una vez más a las historias de usuario [HU2](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/3) y [HU3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/4). 

Una *deuda* debe entenderse al igual que los gastos, *bajo un contexto concreto*, ya que es un objeto que se produce tras la realización de una serie de gastos producidos en un espacio común compartido entre una serie de usuarios participantes. 

Para la representación de una deuda nos encontramos con los siguientes problemas:
* Con respecto [HU3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/4), José Antonio necesita tener un control de a quién le debe dinero y con qué motivo. Se requiere por tanto identificar una deuda con el identificador del usuario a quien se debe dicho importe además de dar un nombre a esa deuda.
* Con respecto [HU2](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/3), María Teresa necesita tener un control de quién ha pagado la deuda que corresponde. Se requiere por tanto habilitar mecanismos que permitan marcar una deuda como pagada.

Una de las consecuencias más directas de estos dos problemas, referido al primero, es que una deuda debe entenderse como la relación entre **única y exclusivamente** dos usuarios participantes, donde uno tiene el rol de usuario que debe, y el otro el que recibe el importe, para que así la aplicación del algoritmo en etapas posteriores sea más sencilla y más eficiente que en el caso de realizar múltiples análisis, provocando resultados minimales entre las deudas de los participantes en un gasto compartido.

(Con minimal, me refiero a que se deben generar las deudas más simples posibles, y por tanto, lo mejor para ello es considerar pares de usuarios, pues que si no es así, es porque se puede seguir dividiendo los gastos).

**Comment by danielsp13** [comment]
Ejemplo basado en el caso de estudio mencionado:
> Clara debe a Isa.

Esto debería traducirse en la siguiente deuda, bajo el contexto del gastoCompartido *Tarde de Merienda*:

**Deuda 1:**
A quien debe: Isa (id)
Quien paga: Clara (id)
Concepto: Tarde de Merienda
Importe: X€
Pagado: False

**Comment by danielsp13** [comment]
@jesusjmma , por favor, asigna este issue a tu milestone M0.

**Comment by JJ** [comment]
> La solución que planteo para esta situación es la definición de un _objeto valor_ denominado **deuda** que contendrá:
> 

La solución se plantea en código, no en un comentario.
