### ISSUE TITLE
[M0 - Dev] Elección de lenguaje de Programación

### ISSUE THREAD

**Issue by danielsp13** [jesusjmma/Proyecto-Infraestructura-Virtual#6]
¡Buenos días Jesús! Soy Dani, y se me ha designado tu proyecto para trabajar en él y avanzar en las tareas para alcanzar el primer hito.

He estado leyendo toda la documentación que has incluido en tu repositorio (un proyecto muy interesante por cierto). De momento, sólo empezaré con este _issue_ que abro para preguntarte acerca del lenguaje de programación que tienes pensado utilizar y la justificación del mismo. 

Espero que sigamos avanzando juntos y cualquier cosa, ¡¡aquí estoy!!
Mucho ánimo y me quedo a la espera :smile: .

**Comment by jesusjmma** [comment]
Hola Dani. No he podido ponerme antes, perdona por la tardanza en contestar.

En el lenguaje he pensado usar Python por varios motivos:
- Facilidad y rapidez de uso
- Puedo usar SQLAlchemy + Migrate para gestionar la base de datos fácilmente desde Python
- No hay que hacer interfaz gráfica en el proyecto (en cuyo caso habría usado otro lenguaje como Typescript)

¿Qué te parece?

**Comment by danielsp13** [comment]
Perfecto, me parece una buena decisión. Intentaré estudiar a lo largo del fin de semana las necesidades del proyecto y abriré nuevos _issues_ para comentarte las decisiones que vaya a ir tomando.

**Comment by danielsp13** [comment]
Este issue tiene asignado la Historia de Usuario [HU3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/4)

**Comment by danielsp13** [comment]
@jesusjmma Te menciono para que cuando puedas, asignes este issue a tu Milestone [M0](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/1)
